services:
  - type: web
    name: wordsnest-admin
    runtime: node
    buildCommand: npm run build
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 22
      - key: GEMINI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROK_API_KEY
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROK_API_KEY_2
        sync: false
